name: sparklines
description: Feature-rich and highly optimized sparklines for Flutter

homepage: https://github.com/andry-brill/a-sparklines
repository: https://github.com/andry-brill/a-sparklines
issue_tracker: https://github.com/andry-brill/a-sparklines/issues

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
